kind: Service
apiVersion: v1

metadata:
  name: backend-service
  namespace: web-ns

spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30777