apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    app: local
  namespace: web-ns
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
